// Auto generated by build.sh at Thu Oct 31 20:20:12 UTC 2013
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("VersionOne.Localization")]
[assembly: AssemblyTitle("VersionOne Localization Library")]
[assembly: AssemblyDescription("Localization and internationalization library with support for multi-layer overrides")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc., Licensed under modified BSD.")]
[assembly: AssemblyVersion("1.0.0.1531")]
[assembly: AssemblyFileVersion("1.0.0.1531")]

[assembly: AssemblyConfiguration("Release")]
